name: interferencernns
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.7.2=hca03da5_0
  - expat=2.6.2=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.14=h80987f9_0
  - pip=24.2=py312hca03da5_0
  - python=3.12.4=h99e199e_1
  - readline=8.2=h1a28f6b_0
  - setuptools=72.1.0=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.43.0=py312hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.65.5
      - h5py==3.11.0
      - idna==3.7
      - joblib==1.4.2
      - keras==3.5.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.0
      - namex==0.0.8
      - numpy==1.26.4
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==24.1
      - pandas==2.2.2
      - patsy==0.5.6
      - pillow==10.4.0
      - protobuf==4.25.4
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - rich==13.7.1
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - six==1.16.0
      - statsmodels==0.14.2
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.16.0
